#!/usr/bin/env sh

TAG=$(grep "version" gradle.properties|cut -d'=' -f2)
TAG=$(echo "$TAG" | tr '[:upper:]' '[:lower:]')

#run container
docker run --rm -p 8080:8080 -v `pwd`/orgs_ignored.yaml:/etc/wonky/tenants.yaml  domix/wonky:$TAG
